/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.essential.rpc.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CommonMessageType implements org.apache.thrift.TEnum {
  MT_HELLO_NOTIFY(100),
  MT_KEEPALIVE_REQ(101),
  MT_KEEPALIVE_RES(102);

  private final int value;

  private CommonMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CommonMessageType findByValue(int value) { 
    switch (value) {
      case 100:
        return MT_HELLO_NOTIFY;
      case 101:
        return MT_KEEPALIVE_REQ;
      case 102:
        return MT_KEEPALIVE_RES;
      default:
        return null;
    }
  }
}
