/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.essential.rpc.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  OK(0),
  LOGIN_FAILED(100),
  LOGNAME_EXIST(101),
  LOGNAME_NOT_EXIST(102),
  PASSWORD_ERROR(103),
  SERVICE_REGISTER_FAILED(104);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 100:
        return LOGIN_FAILED;
      case 101:
        return LOGNAME_EXIST;
      case 102:
        return LOGNAME_NOT_EXIST;
      case 103:
        return PASSWORD_ERROR;
      case 104:
        return SERVICE_REGISTER_FAILED;
      default:
        return null;
    }
  }
}
