/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.essential.rpc.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LoginMessageType implements org.apache.thrift.TEnum {
  MT_CLIENT_PASSWORD_LOGIN_REQ(500),
  MT_CLIENT_LOGIN_RES(501),
  MT_CLIENT_LOGOUT_REQ(502),
  MT_CLIENT_LOGOUT_RES(503);

  private final int value;

  private LoginMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LoginMessageType findByValue(int value) { 
    switch (value) {
      case 500:
        return MT_CLIENT_PASSWORD_LOGIN_REQ;
      case 501:
        return MT_CLIENT_LOGIN_RES;
      case 502:
        return MT_CLIENT_LOGOUT_REQ;
      case 503:
        return MT_CLIENT_LOGOUT_RES;
      default:
        return null;
    }
  }
}
