/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.essential.rpc.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ProviderMessageType implements org.apache.thrift.TEnum {
  MT_SERVICE_REGISTER_REQ(1200),
  MT_SERVICE_REGISTER_RES(1201);

  private final int value;

  private ProviderMessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ProviderMessageType findByValue(int value) { 
    switch (value) {
      case 1200:
        return MT_SERVICE_REGISTER_REQ;
      case 1201:
        return MT_SERVICE_REGISTER_RES;
      default:
        return null;
    }
  }
}
