/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.thrift.socketserver.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-08-21")
public class ApplicationInfo implements org.apache.thrift.TBase<ApplicationInfo, ApplicationInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ApplicationInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ApplicationInfo");

  private static final org.apache.thrift.protocol.TField SUCCESS_RATE_FIELD_DESC = new org.apache.thrift.protocol.TField("success_rate", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField SERVICE_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("service_number", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ApplicationInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ApplicationInfoTupleSchemeFactory();

  public double success_rate; // required
  public long service_number; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUCCESS_RATE((short)1, "success_rate"),
    SERVICE_NUMBER((short)2, "service_number");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SUCCESS_RATE
          return SUCCESS_RATE;
        case 2: // SERVICE_NUMBER
          return SERVICE_NUMBER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SUCCESS_RATE_ISSET_ID = 0;
  private static final int __SERVICE_NUMBER_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUCCESS_RATE, new org.apache.thrift.meta_data.FieldMetaData("success_rate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.SERVICE_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("service_number", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ApplicationInfo.class, metaDataMap);
  }

  public ApplicationInfo() {
  }

  public ApplicationInfo(
    double success_rate,
    long service_number)
  {
    this();
    this.success_rate = success_rate;
    setSuccess_rateIsSet(true);
    this.service_number = service_number;
    setService_numberIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ApplicationInfo(ApplicationInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.success_rate = other.success_rate;
    this.service_number = other.service_number;
  }

  public ApplicationInfo deepCopy() {
    return new ApplicationInfo(this);
  }

  @Override
  public void clear() {
    setSuccess_rateIsSet(false);
    this.success_rate = 0.0;
    setService_numberIsSet(false);
    this.service_number = 0;
  }

  public double getSuccess_rate() {
    return this.success_rate;
  }

  public ApplicationInfo setSuccess_rate(double success_rate) {
    this.success_rate = success_rate;
    setSuccess_rateIsSet(true);
    return this;
  }

  public void unsetSuccess_rate() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_RATE_ISSET_ID);
  }

  /** Returns true if field success_rate is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess_rate() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUCCESS_RATE_ISSET_ID);
  }

  public void setSuccess_rateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUCCESS_RATE_ISSET_ID, value);
  }

  public long getService_number() {
    return this.service_number;
  }

  public ApplicationInfo setService_number(long service_number) {
    this.service_number = service_number;
    setService_numberIsSet(true);
    return this;
  }

  public void unsetService_number() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVICE_NUMBER_ISSET_ID);
  }

  /** Returns true if field service_number is set (has been assigned a value) and false otherwise */
  public boolean isSetService_number() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVICE_NUMBER_ISSET_ID);
  }

  public void setService_numberIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVICE_NUMBER_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case SUCCESS_RATE:
      if (value == null) {
        unsetSuccess_rate();
      } else {
        setSuccess_rate((java.lang.Double)value);
      }
      break;

    case SERVICE_NUMBER:
      if (value == null) {
        unsetService_number();
      } else {
        setService_number((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SUCCESS_RATE:
      return getSuccess_rate();

    case SERVICE_NUMBER:
      return getService_number();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SUCCESS_RATE:
      return isSetSuccess_rate();
    case SERVICE_NUMBER:
      return isSetService_number();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ApplicationInfo)
      return this.equals((ApplicationInfo)that);
    return false;
  }

  public boolean equals(ApplicationInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_success_rate = true;
    boolean that_present_success_rate = true;
    if (this_present_success_rate || that_present_success_rate) {
      if (!(this_present_success_rate && that_present_success_rate))
        return false;
      if (this.success_rate != that.success_rate)
        return false;
    }

    boolean this_present_service_number = true;
    boolean that_present_service_number = true;
    if (this_present_service_number || that_present_service_number) {
      if (!(this_present_service_number && that_present_service_number))
        return false;
      if (this.service_number != that.service_number)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(success_rate);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(service_number);

    return hashCode;
  }

  @Override
  public int compareTo(ApplicationInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetSuccess_rate()).compareTo(other.isSetSuccess_rate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess_rate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success_rate, other.success_rate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetService_number()).compareTo(other.isSetService_number());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetService_number()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.service_number, other.service_number);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ApplicationInfo(");
    boolean first = true;

    sb.append("success_rate:");
    sb.append(this.success_rate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("service_number:");
    sb.append(this.service_number);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ApplicationInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ApplicationInfoStandardScheme getScheme() {
      return new ApplicationInfoStandardScheme();
    }
  }

  private static class ApplicationInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ApplicationInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ApplicationInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SUCCESS_RATE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.success_rate = iprot.readDouble();
              struct.setSuccess_rateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SERVICE_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.service_number = iprot.readI64();
              struct.setService_numberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ApplicationInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SUCCESS_RATE_FIELD_DESC);
      oprot.writeDouble(struct.success_rate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SERVICE_NUMBER_FIELD_DESC);
      oprot.writeI64(struct.service_number);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ApplicationInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ApplicationInfoTupleScheme getScheme() {
      return new ApplicationInfoTupleScheme();
    }
  }

  private static class ApplicationInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ApplicationInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ApplicationInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSuccess_rate()) {
        optionals.set(0);
      }
      if (struct.isSetService_number()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSuccess_rate()) {
        oprot.writeDouble(struct.success_rate);
      }
      if (struct.isSetService_number()) {
        oprot.writeI64(struct.service_number);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ApplicationInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.success_rate = iprot.readDouble();
        struct.setSuccess_rateIsSet(true);
      }
      if (incoming.get(1)) {
        struct.service_number = iprot.readI64();
        struct.setService_numberIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

