package com.spirit.thrift.socketserver.rpc.thrift; /**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MessageType implements TEnum {
  MT_SERVICE_LIST_REQ(1000),
  MT_SERVICE_LIST_RES(1001),
  MT_SERVICE_LIST_CHANGE_NOTIFY(1002),
  MT_SERVICE_LIST_CHANGE_RES(1003);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageType findByValue(int value) { 
    switch (value) {
      case 1000:
        return MT_SERVICE_LIST_REQ;
      case 1001:
        return MT_SERVICE_LIST_RES;
      case 1002:
        return MT_SERVICE_LIST_CHANGE_NOTIFY;
      case 1003:
        return MT_SERVICE_LIST_CHANGE_RES;
      default:
        return null;
    }
  }
}
