/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.thrift.socketserver.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-08-21")
public class ServiceListSyncNotify implements org.apache.thrift.TBase<ServiceListSyncNotify, ServiceListSyncNotify._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceListSyncNotify> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceListSyncNotify");

  private static final org.apache.thrift.protocol.TField SERVICE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("service_id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SERVICE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("service_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField INFO_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("info_list", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceListSyncNotifyStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceListSyncNotifyTupleSchemeFactory();

  public int service_id; // required
  public java.lang.String service_name; // required
  public int type; // required
  public java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> info_list; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SERVICE_ID((short)1, "service_id"),
    SERVICE_NAME((short)2, "service_name"),
    TYPE((short)3, "type"),
    INFO_LIST((short)4, "info_list");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SERVICE_ID
          return SERVICE_ID;
        case 2: // SERVICE_NAME
          return SERVICE_NAME;
        case 3: // TYPE
          return TYPE;
        case 4: // INFO_LIST
          return INFO_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SERVICE_ID_ISSET_ID = 0;
  private static final int __TYPE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SERVICE_ID, new org.apache.thrift.meta_data.FieldMetaData("service_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SERVICE_NAME, new org.apache.thrift.meta_data.FieldMetaData("service_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.INFO_LIST, new org.apache.thrift.meta_data.FieldMetaData("info_list", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceListSyncNotify.class, metaDataMap);
  }

  public ServiceListSyncNotify() {
  }

  public ServiceListSyncNotify(
    int service_id,
    java.lang.String service_name,
    int type,
    java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> info_list)
  {
    this();
    this.service_id = service_id;
    setService_idIsSet(true);
    this.service_name = service_name;
    this.type = type;
    setTypeIsSet(true);
    this.info_list = info_list;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServiceListSyncNotify(ServiceListSyncNotify other) {
    __isset_bitfield = other.__isset_bitfield;
    this.service_id = other.service_id;
    if (other.isSetService_name()) {
      this.service_name = other.service_name;
    }
    this.type = other.type;
    if (other.isSetInfo_list()) {
      java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> __this__info_list = new java.util.ArrayList<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo>(other.info_list.size());
      for (com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo other_element : other.info_list) {
        __this__info_list.add(new com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo(other_element));
      }
      this.info_list = __this__info_list;
    }
  }

  public ServiceListSyncNotify deepCopy() {
    return new ServiceListSyncNotify(this);
  }

  @Override
  public void clear() {
    setService_idIsSet(false);
    this.service_id = 0;
    this.service_name = null;
    setTypeIsSet(false);
    this.type = 0;
    this.info_list = null;
  }

  public int getService_id() {
    return this.service_id;
  }

  public ServiceListSyncNotify setService_id(int service_id) {
    this.service_id = service_id;
    setService_idIsSet(true);
    return this;
  }

  public void unsetService_id() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVICE_ID_ISSET_ID);
  }

  /** Returns true if field service_id is set (has been assigned a value) and false otherwise */
  public boolean isSetService_id() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVICE_ID_ISSET_ID);
  }

  public void setService_idIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVICE_ID_ISSET_ID, value);
  }

  public java.lang.String getService_name() {
    return this.service_name;
  }

  public ServiceListSyncNotify setService_name(java.lang.String service_name) {
    this.service_name = service_name;
    return this;
  }

  public void unsetService_name() {
    this.service_name = null;
  }

  /** Returns true if field service_name is set (has been assigned a value) and false otherwise */
  public boolean isSetService_name() {
    return this.service_name != null;
  }

  public void setService_nameIsSet(boolean value) {
    if (!value) {
      this.service_name = null;
    }
  }

  public int getType() {
    return this.type;
  }

  public ServiceListSyncNotify setType(int type) {
    this.type = type;
    setTypeIsSet(true);
    return this;
  }

  public void unsetType() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  public void setTypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TYPE_ISSET_ID, value);
  }

  public int getInfo_listSize() {
    return (this.info_list == null) ? 0 : this.info_list.size();
  }

  public java.util.Iterator<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> getInfo_listIterator() {
    return (this.info_list == null) ? null : this.info_list.iterator();
  }

  public void addToInfo_list(com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo elem) {
    if (this.info_list == null) {
      this.info_list = new java.util.ArrayList<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo>();
    }
    this.info_list.add(elem);
  }

  public java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> getInfo_list() {
    return this.info_list;
  }

  public ServiceListSyncNotify setInfo_list(java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo> info_list) {
    this.info_list = info_list;
    return this;
  }

  public void unsetInfo_list() {
    this.info_list = null;
  }

  /** Returns true if field info_list is set (has been assigned a value) and false otherwise */
  public boolean isSetInfo_list() {
    return this.info_list != null;
  }

  public void setInfo_listIsSet(boolean value) {
    if (!value) {
      this.info_list = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case SERVICE_ID:
      if (value == null) {
        unsetService_id();
      } else {
        setService_id((java.lang.Integer)value);
      }
      break;

    case SERVICE_NAME:
      if (value == null) {
        unsetService_name();
      } else {
        setService_name((java.lang.String)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((java.lang.Integer)value);
      }
      break;

    case INFO_LIST:
      if (value == null) {
        unsetInfo_list();
      } else {
        setInfo_list((java.util.List<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SERVICE_ID:
      return getService_id();

    case SERVICE_NAME:
      return getService_name();

    case TYPE:
      return getType();

    case INFO_LIST:
      return getInfo_list();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SERVICE_ID:
      return isSetService_id();
    case SERVICE_NAME:
      return isSetService_name();
    case TYPE:
      return isSetType();
    case INFO_LIST:
      return isSetInfo_list();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ServiceListSyncNotify)
      return this.equals((ServiceListSyncNotify)that);
    return false;
  }

  public boolean equals(ServiceListSyncNotify that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_service_id = true;
    boolean that_present_service_id = true;
    if (this_present_service_id || that_present_service_id) {
      if (!(this_present_service_id && that_present_service_id))
        return false;
      if (this.service_id != that.service_id)
        return false;
    }

    boolean this_present_service_name = true && this.isSetService_name();
    boolean that_present_service_name = true && that.isSetService_name();
    if (this_present_service_name || that_present_service_name) {
      if (!(this_present_service_name && that_present_service_name))
        return false;
      if (!this.service_name.equals(that.service_name))
        return false;
    }

    boolean this_present_type = true;
    boolean that_present_type = true;
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (this.type != that.type)
        return false;
    }

    boolean this_present_info_list = true && this.isSetInfo_list();
    boolean that_present_info_list = true && that.isSetInfo_list();
    if (this_present_info_list || that_present_info_list) {
      if (!(this_present_info_list && that_present_info_list))
        return false;
      if (!this.info_list.equals(that.info_list))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + service_id;

    hashCode = hashCode * 8191 + ((isSetService_name()) ? 131071 : 524287);
    if (isSetService_name())
      hashCode = hashCode * 8191 + service_name.hashCode();

    hashCode = hashCode * 8191 + type;

    hashCode = hashCode * 8191 + ((isSetInfo_list()) ? 131071 : 524287);
    if (isSetInfo_list())
      hashCode = hashCode * 8191 + info_list.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ServiceListSyncNotify other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetService_id()).compareTo(other.isSetService_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetService_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.service_id, other.service_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetService_name()).compareTo(other.isSetService_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetService_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.service_name, other.service_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetInfo_list()).compareTo(other.isSetInfo_list());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInfo_list()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.info_list, other.info_list);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ServiceListSyncNotify(");
    boolean first = true;

    sb.append("service_id:");
    sb.append(this.service_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("service_name:");
    if (this.service_name == null) {
      sb.append("null");
    } else {
      sb.append(this.service_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("type:");
    sb.append(this.type);
    first = false;
    if (!first) sb.append(", ");
    sb.append("info_list:");
    if (this.info_list == null) {
      sb.append("null");
    } else {
      sb.append(this.info_list);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServiceListSyncNotifyStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServiceListSyncNotifyStandardScheme getScheme() {
      return new ServiceListSyncNotifyStandardScheme();
    }
  }

  private static class ServiceListSyncNotifyStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceListSyncNotify> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceListSyncNotify struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SERVICE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.service_id = iprot.readI32();
              struct.setService_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SERVICE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.service_name = iprot.readString();
              struct.setService_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = iprot.readI32();
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // INFO_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.info_list = new java.util.ArrayList<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo>(_list8.size);
                com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo();
                  _elem9.read(iprot);
                  struct.info_list.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setInfo_listIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceListSyncNotify struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SERVICE_ID_FIELD_DESC);
      oprot.writeI32(struct.service_id);
      oprot.writeFieldEnd();
      if (struct.service_name != null) {
        oprot.writeFieldBegin(SERVICE_NAME_FIELD_DESC);
        oprot.writeString(struct.service_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TYPE_FIELD_DESC);
      oprot.writeI32(struct.type);
      oprot.writeFieldEnd();
      if (struct.info_list != null) {
        oprot.writeFieldBegin(INFO_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.info_list.size()));
          for (com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo _iter11 : struct.info_list)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServiceListSyncNotifyTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServiceListSyncNotifyTupleScheme getScheme() {
      return new ServiceListSyncNotifyTupleScheme();
    }
  }

  private static class ServiceListSyncNotifyTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceListSyncNotify> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServiceListSyncNotify struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetService_id()) {
        optionals.set(0);
      }
      if (struct.isSetService_name()) {
        optionals.set(1);
      }
      if (struct.isSetType()) {
        optionals.set(2);
      }
      if (struct.isSetInfo_list()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetService_id()) {
        oprot.writeI32(struct.service_id);
      }
      if (struct.isSetService_name()) {
        oprot.writeString(struct.service_name);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type);
      }
      if (struct.isSetInfo_list()) {
        {
          oprot.writeI32(struct.info_list.size());
          for (com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo _iter12 : struct.info_list)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServiceListSyncNotify struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.service_id = iprot.readI32();
        struct.setService_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.service_name = iprot.readString();
        struct.setService_nameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.type = iprot.readI32();
        struct.setTypeIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.info_list = new java.util.ArrayList<com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo>(_list13.size);
          com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new com.spirit.thrift.socketserver.rpc.thrift.ServiceRouteInfo();
            _elem14.read(iprot);
            struct.info_list.add(_elem14);
          }
        }
        struct.setInfo_listIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

