/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spirit.thrift.socketserver.rpc.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-08-21")
public class ServiceQuality implements org.apache.thrift.TBase<ServiceQuality, ServiceQuality._Fields>, java.io.Serializable, Cloneable, Comparable<ServiceQuality> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServiceQuality");

  private static final org.apache.thrift.protocol.TField APP_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("app_info", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField SYS_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("sys_info", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServiceQualityStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServiceQualityTupleSchemeFactory();

  public ApplicationInfo app_info; // required
  public SystemInfo sys_info; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    APP_INFO((short)1, "app_info"),
    SYS_INFO((short)2, "sys_info");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // APP_INFO
          return APP_INFO;
        case 2: // SYS_INFO
          return SYS_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.APP_INFO, new org.apache.thrift.meta_data.FieldMetaData("app_info", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ApplicationInfo.class)));
    tmpMap.put(_Fields.SYS_INFO, new org.apache.thrift.meta_data.FieldMetaData("sys_info", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SystemInfo.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServiceQuality.class, metaDataMap);
  }

  public ServiceQuality() {
  }

  public ServiceQuality(
    ApplicationInfo app_info,
    SystemInfo sys_info)
  {
    this();
    this.app_info = app_info;
    this.sys_info = sys_info;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServiceQuality(ServiceQuality other) {
    if (other.isSetApp_info()) {
      this.app_info = new ApplicationInfo(other.app_info);
    }
    if (other.isSetSys_info()) {
      this.sys_info = new SystemInfo(other.sys_info);
    }
  }

  public ServiceQuality deepCopy() {
    return new ServiceQuality(this);
  }

  @Override
  public void clear() {
    this.app_info = null;
    this.sys_info = null;
  }

  public ApplicationInfo getApp_info() {
    return this.app_info;
  }

  public ServiceQuality setApp_info(ApplicationInfo app_info) {
    this.app_info = app_info;
    return this;
  }

  public void unsetApp_info() {
    this.app_info = null;
  }

  /** Returns true if field app_info is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_info() {
    return this.app_info != null;
  }

  public void setApp_infoIsSet(boolean value) {
    if (!value) {
      this.app_info = null;
    }
  }

  public SystemInfo getSys_info() {
    return this.sys_info;
  }

  public ServiceQuality setSys_info(SystemInfo sys_info) {
    this.sys_info = sys_info;
    return this;
  }

  public void unsetSys_info() {
    this.sys_info = null;
  }

  /** Returns true if field sys_info is set (has been assigned a value) and false otherwise */
  public boolean isSetSys_info() {
    return this.sys_info != null;
  }

  public void setSys_infoIsSet(boolean value) {
    if (!value) {
      this.sys_info = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case APP_INFO:
      if (value == null) {
        unsetApp_info();
      } else {
        setApp_info((ApplicationInfo)value);
      }
      break;

    case SYS_INFO:
      if (value == null) {
        unsetSys_info();
      } else {
        setSys_info((SystemInfo)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case APP_INFO:
      return getApp_info();

    case SYS_INFO:
      return getSys_info();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case APP_INFO:
      return isSetApp_info();
    case SYS_INFO:
      return isSetSys_info();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ServiceQuality)
      return this.equals((ServiceQuality)that);
    return false;
  }

  public boolean equals(ServiceQuality that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_app_info = true && this.isSetApp_info();
    boolean that_present_app_info = true && that.isSetApp_info();
    if (this_present_app_info || that_present_app_info) {
      if (!(this_present_app_info && that_present_app_info))
        return false;
      if (!this.app_info.equals(that.app_info))
        return false;
    }

    boolean this_present_sys_info = true && this.isSetSys_info();
    boolean that_present_sys_info = true && that.isSetSys_info();
    if (this_present_sys_info || that_present_sys_info) {
      if (!(this_present_sys_info && that_present_sys_info))
        return false;
      if (!this.sys_info.equals(that.sys_info))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetApp_info()) ? 131071 : 524287);
    if (isSetApp_info())
      hashCode = hashCode * 8191 + app_info.hashCode();

    hashCode = hashCode * 8191 + ((isSetSys_info()) ? 131071 : 524287);
    if (isSetSys_info())
      hashCode = hashCode * 8191 + sys_info.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ServiceQuality other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetApp_info()).compareTo(other.isSetApp_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.app_info, other.app_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSys_info()).compareTo(other.isSetSys_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSys_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sys_info, other.sys_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ServiceQuality(");
    boolean first = true;

    sb.append("app_info:");
    if (this.app_info == null) {
      sb.append("null");
    } else {
      sb.append(this.app_info);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sys_info:");
    if (this.sys_info == null) {
      sb.append("null");
    } else {
      sb.append(this.sys_info);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (app_info != null) {
      app_info.validate();
    }
    if (sys_info != null) {
      sys_info.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServiceQualityStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServiceQualityStandardScheme getScheme() {
      return new ServiceQualityStandardScheme();
    }
  }

  private static class ServiceQualityStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServiceQuality> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServiceQuality struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // APP_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.app_info = new ApplicationInfo();
              struct.app_info.read(iprot);
              struct.setApp_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SYS_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.sys_info = new SystemInfo();
              struct.sys_info.read(iprot);
              struct.setSys_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServiceQuality struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.app_info != null) {
        oprot.writeFieldBegin(APP_INFO_FIELD_DESC);
        struct.app_info.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.sys_info != null) {
        oprot.writeFieldBegin(SYS_INFO_FIELD_DESC);
        struct.sys_info.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServiceQualityTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServiceQualityTupleScheme getScheme() {
      return new ServiceQualityTupleScheme();
    }
  }

  private static class ServiceQualityTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServiceQuality> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServiceQuality struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetApp_info()) {
        optionals.set(0);
      }
      if (struct.isSetSys_info()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetApp_info()) {
        struct.app_info.write(oprot);
      }
      if (struct.isSetSys_info()) {
        struct.sys_info.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServiceQuality struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.app_info = new ApplicationInfo();
        struct.app_info.read(iprot);
        struct.setApp_infoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sys_info = new SystemInfo();
        struct.sys_info.read(iprot);
        struct.setSys_infoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

